import { createFileRoute, Link } from "@tanstack/react-router";
import { LegalList, LegalPage, LegalSection, SupportLink } from "@/components/legal-page";

const TITLE = "Terms of Service · ResearchMind Lab";
const SUMMARY =
  "The terms you agree to when you use ResearchMind Lab: your account, the papers you upload, the limits of AI-generated output, and governing law.";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: SUMMARY },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: SUMMARY },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="16 September 2026">
      <LegalSection title="Who these terms are with">
        <p>
          ResearchMind Lab is operated by Harish Kumar S G, an individual based in India. By
          creating an account or using the service you agree to these terms. If you do not agree
          with them, please do not use the service.
        </p>
      </LegalSection>

      <LegalSection title="Who may use it">
        <p>
          You must be at least 16 years old. By signing in you confirm that you are, and that the
          information your Google account provides is your own.
        </p>
      </LegalSection>

      <LegalSection title="What the service does">
        <p>
          ResearchMind Lab lets you upload PDF research papers, indexes them so they can be searched
          by meaning, answers questions using passages retrieved from those papers, compares two
          papers, and drafts literature reviews with citations that you can export as a PDF.
        </p>
        <p>It answers from the papers in your own library, not from the open web.</p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          Accounts are created by signing in with Google. You are responsible for keeping access to
          that Google account secure, and for activity that happens under your ResearchMind Lab
          account. Tell me at <SupportLink /> if you think someone else has gained access.
        </p>
      </LegalSection>

      <LegalSection title="The papers you upload">
        <p>
          You keep ownership of everything you upload. Nothing here transfers your rights, or the
          rights of the authors and publishers of the papers, to me.
        </p>
        <p>
          You may upload a paper only if you have the necessary rights or permission to upload it
          and to have it processed as described in these terms. Many published papers are subject to
          copyright and to publisher or institutional licence terms that limit how they may be
          copied or shared, and it is your responsibility to check that your use is permitted. Do
          not upload material you are not allowed to.
        </p>
        <p>
          Signing in with Google confirms who you are and nothing more. It grants no rights over any
          paper, and never replaces the permission you need from the rights holder.
        </p>
        <p>
          By uploading, you permit me to store the file, extract and split its text, create
          embeddings of it, and send relevant passages to the AI providers named in the{" "}
          <Link className="text-primary underline underline-offset-4" to="/privacy">
            Privacy Policy
          </Link>
          , strictly to provide the features you are using.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <LegalList
          items={[
            "Do not upload unlawful material, malware, or content you have no right to use.",
            "Do not try to reach another user's papers, chats, reports or account.",
            "Do not attempt to break, overload, probe or circumvent the service's security or its usage limits.",
            "Do not use the service to produce work you then present as original research without checking and citing the underlying sources.",
          ]}
        />
      </LegalSection>

      <LegalSection title="AI-generated output">
        <p>
          Answers, comparisons and reports are generated by a language model from passages retrieved
          out of your papers. They can be incomplete, mistaken, or confidently wrong, and citations
          can point at the wrong place.
        </p>
        <p>
          Treat the output as a guide to your sources, never as a source in itself. Open the pages
          it cites and verify them before relying on or publishing anything. The output is not
          professional, legal, medical or academic advice, and you remain responsible for any work
          you produce with it.
        </p>
      </LegalSection>

      <LegalSection title="Availability and changes">
        <p>
          The service is free at the moment. It may become paid in future; if that happens, existing
          users will be told before any charge applies.
        </p>
        <p>
          It is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis, with no
          uptime guarantee. Features may change or be withdrawn, and the service may be suspended or
          discontinued. Keep your own copies of any paper or report that matters to you rather than
          treating this as your only store.
        </p>
      </LegalSection>

      <LegalSection title="Ending your use">
        <p>
          You may stop at any time, delete individual papers from within the app, or email{" "}
          <SupportLink /> to have your account and its data deleted.
        </p>
        <p>
          I may suspend or remove an account that breaches these terms, that puts other users or the
          service at risk, or where required by law. Where it is reasonable to do so, I will say
          why.
        </p>
      </LegalSection>

      <LegalSection title="Liability">
        <p>
          To the fullest extent permitted by law, I am not liable for indirect or consequential
          loss, for lost profits or opportunities, for loss of data, or for decisions taken in
          reliance on AI-generated output.
        </p>
        <p>
          Nothing in these terms limits liability that cannot be limited by law, including liability
          for death or personal injury caused by negligence, or for fraud.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          Updated terms appear on this page with a new date at the top. Continuing to use the
          service after a change means you accept the revised terms.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          These terms are governed by the laws of India, and the courts of Tamil Nadu, India have
          exclusive jurisdiction over any dispute arising from them or from your use of the service.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these terms go to <SupportLink />, or see the{" "}
          <Link className="text-primary underline underline-offset-4" to="/contact">
            contact page
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
